#!/home/fodl/asafmaman/anaconda3/envs/pet/bin/python
import sys
import argparse

from common.utils import parse_dir_results


def main():
    parser = argparse.ArgumentParser()

    parser.add_argument('path')
    parser.add_argument('--verbose', default=False, action='store_true')
    parser.add_argument('--save', default=False, action='store_true')
    parser.add_argument('--override', default=False, action='store_true')


    args = parser.parse_args()

    parse_dir_results(**args.__dict__)


if __name__ == '__main__':
    main()
